---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-container
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: naveen184/my-app:latest
          ports:
            - containerPort: 80
