
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-container
  namespace: argocd
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: 779372627864.dkr.ecr.ap-south-1.amazonaws.com/mean-demo:latest
          ports:
            - containerPort: 80
