
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-container
  namespace: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-container
          imagePullPolicy: Always
          image: telus121/my-app:latest
          ports:
            - containerPort: 80
