---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ravindrasinghh/argocd-setup.git
  sshPrivateKey: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8myc0zLBptNVRYICTS6ZrlQv6RKEvdzEJqKtzHlTX3zbNq8YwC/EL0QQfUTvBEN8wySfPNzKXY5xHXkZnATiLt88PjYwNCvcf8KGEzKRHcU6cv7TTzmbn2KHon0n7E/RdlysBtNOPDz6oEFLAHvuUnFQJ7PYzQ4FNPYq53PJfhSQbk1h4rJnkE+GT5VjtJzn4j9T1lGgtq9NBj/e3vDGzH+MnUpkxWYrnR0kpxwB3b8xMCLhqeq4McXpz+ryhezvUPXd2bm+r6BUcgtyn0PtoSxmcEzfcSaCvgzFTXCm5T7gvXUuAXdemSuyWHn/McT76X9S8w+1qNqba5uyGE0dg3pU1CPuzRVe378Tsl40kOis7ZtpuSdFCdPe+93edO0Dnv16ItX6Zxg29HHvRdTo2QLty1KKDZHct0jamYgx48OEsqlScekgBmBSpKxiKQtvFbqV+Gsg0ScyQJSILvYYpK1uvkzZ01egq0xucy/PKF9bPQt5s/s5NDE7KQfjkrsE= xavient@Xavients-MacBook-Pro.local
  insecure: "false"
  enableLfs: "true"


# command to generate key
# ssh-keygen -t ed25519 -f ~/.ssh/argocd

